server:
  port: 8888
  servlet:
    context-path: /netflow

spring:
  datasource:
    one:
      jdbcUrl: jdbc:mysql://localhost:3306/authority?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
      username: wpl
      password: yyanmc233..
    two:
      jdbcUrl: jdbc:mysql://localhost:3306/authority?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=true
      username: wpl
      password: yyanmc233..

authority:
  jwt:
    expire: 600000
    secret: newflow_token